### ISSUE TITLE
Reactive api rest for get SVG

### ISSUE THREAD

**Issue by davideduma** [serverlessworkflow/sdk-java#216]
**What would you like to be added**:
Reactive api rest for get SVG
**Why is this needed**:
Interact with the application without unit tests

**Comment by tsurdilo** [comment]
@davideduma merged your pr, ty again. Please take a look at https://github.com/serverlessworkflow/sdk-java/commit/5809c62872c45232cff1db2658780ac0e1efbf16

make some simplifications to the code and i make it its own module rather than being part of main modules as it does not use the same parent pom and we cannot thus make it part of a sdk release.

also added update to main readme

one thing id like to ask, it would be really nice to change the response to be actual svg xml and not json that includes the svg as value of the "result" response element. let me know if this is something you want to work on. thanks!

**Comment by tsurdilo** [comment]
made the small change to have the svg xml direct result rather than json - https://github.com/serverlessworkflow/sdk-java/pull/219

thanks again for great contribution

**Comment by davideduma** [comment]
@tsurdilo 

I'm happy that PR it was accept and to know that is helpful.
I hope to continue contribute in this project.
