### ISSUE TITLE
grantType "resourceOwner" mentioned in 0.8 but not supported in sdk

### ISSUE THREAD

**Issue by mahith2108** [serverlessworkflow/sdk-java#364]
**What is the question**:
GrantType "resourceOwner" is not supported by 4.0.5 java sdk but the spec 0.8 refers to "resourceOwner" for userName field

https://github.com/serverlessworkflow/specification/blob/0.8.x/specification.md#oauth2-properties-definition
 https://github.com/serverlessworkflow/specification/blob/0.8.x/schema/auth.json#L191

    public static enum GrantType {
        PASSWORD("password"),
        CLIENT_CREDENTIALS("clientCredentials"),
        TOKEN_EXCHANGE("tokenExchange");

        private final String value;

**Comment by ricardozanini** [comment]
@mahith2108 can you open a PR? I'm releasing version 5.0.0.Final at this moment. Once we have yours, I can patch and do a 5.0.1 release for you.

**Comment by mahith2108** [comment]
Sure Will raise PR

**Comment by mahith2108** [comment]
PR: https://github.com/serverlessworkflow/sdk-java/issues/369

**Comment by ricardozanini** [comment]
@mahith2108 thanks, but this is an issue, not a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests).

I'm gonna close it since this issue already reports this bug. Also, can you please try it with [5.0.0](https://mvnrepository.com/artifact/io.serverlessworkflow/serverlessworkflow-api/5.0.0.Final)?
